// Code generated by tools/placetime13d-generate; DO NOT EDIT.
package placetime13d

const GeneratedRegistryRoot = "sha256:b63e16c073c0c3b58f277787b033fa25132b1e21be59a371312962f68953c913"

var GeneratedDimensions = []DimensionDescriptor{
	{ID: "d01", Name: "observed_time", CoordinateClass: "spacetime-observation"},
	{ID: "d02", Name: "latitude", CoordinateClass: "spacetime-observation"},
	{ID: "d03", Name: "longitude", CoordinateClass: "spacetime-observation"},
	{ID: "d04", Name: "vertical_coordinate", CoordinateClass: "spacetime-observation"},
	{ID: "d05", Name: "semantic_axis_1", CoordinateClass: "semantic-provenance"},
	{ID: "d06", Name: "semantic_axis_2", CoordinateClass: "semantic-provenance"},
	{ID: "d07", Name: "provenance_integrity_index", CoordinateClass: "semantic-provenance"},
	{ID: "d08", Name: "lineage_commitment", CoordinateClass: "semantic-provenance"},
	{ID: "d09", Name: "observer_confidence", CoordinateClass: "observation-context"},
	{ID: "d10", Name: "instrumentation_class", CoordinateClass: "observation-context"},
	{ID: "d11", Name: "certifier_reference", CoordinateClass: "observation-context"},
	{ID: "d12", Name: "claim_radius", CoordinateClass: "governance-boundary"},
	{ID: "d13", Name: "entity_binding", CoordinateClass: "governance-boundary"},
}
