package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

type registry struct {
	Schema          string                     `json:"schema"`
	Version         string                     `json:"version"`
	Status          string                     `json:"status"`
	AuthorityEffect string                     `json:"authorityEffect"`
	Dimensions      []dimension                `json:"dimensions"`
	Definitions     map[string]json.RawMessage `json:"$defs"`
}

type dimension struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	CoordinateClass string          `json:"coordinateClass"`
	Definition      string          `json:"definition"`
	NullMeaning     string          `json:"nullMeaning"`
	ValueSchema     json.RawMessage `json:"valueSchema"`
	DerivedMetrics  []string        `json:"derivedMetrics"`
}

func main() {
	registryPath := flag.String("registry", "registry/13D_coordinates.yaml", "source registry")
	goOutput := flag.String("go-output", "internal/placetime13d/registry_generated.go", "generated Go registry")
	schemaOutput := flag.String("schema-output", "registry/event_envelope.schema.json", "generated event schema")
	check := flag.Bool("check", false, "fail if generated outputs are stale")
	flag.Parse()

	source, err := os.ReadFile(*registryPath)
	fatalIf(err)
	var parsed registry
	fatalIf(json.Unmarshal(source, &parsed))
	fatalIf(validateRegistry(parsed))

	root := sha256.Sum256(source)
	registryRoot := "sha256:" + hex.EncodeToString(root[:])
	goBytes, err := generateGo(parsed, registryRoot)
	fatalIf(err)
	schemaBytes, err := generateSchema(parsed, registryRoot)
	fatalIf(err)

	if *check {
		fatalIf(compareFile(*goOutput, goBytes))
		fatalIf(compareFile(*schemaOutput, schemaBytes))
		return
	}
	fatalIf(writeFile(*goOutput, goBytes))
	fatalIf(writeFile(*schemaOutput, schemaBytes))
}

func validateRegistry(value registry) error {
	if value.Schema != "urn:logos-formal:placetime-13d-registry:v0.1" {
		return fmt.Errorf("unexpected registry schema %q", value.Schema)
	}
	if value.Version != "0.1.0" || value.Status != "PROPOSED" || value.AuthorityEffect != "NONE" {
		return errors.New("registry version, status, or authority fence is invalid")
	}
	if len(value.Dimensions) != 13 {
		return fmt.Errorf("registry has %d dimensions, want 13", len(value.Dimensions))
	}
	seenNames := map[string]bool{}
	for index, item := range value.Dimensions {
		expected := fmt.Sprintf("d%02d", index+1)
		if item.ID != expected {
			return fmt.Errorf("dimension %d has id %q, want %q", index, item.ID, expected)
		}
		if item.Name == "" || item.CoordinateClass == "" || item.Definition == "" || item.NullMeaning == "" {
			return fmt.Errorf("%s contains an empty required field", item.ID)
		}
		if seenNames[item.Name] {
			return fmt.Errorf("duplicate dimension name %q", item.Name)
		}
		seenNames[item.Name] = true
		if len(item.ValueSchema) == 0 || !json.Valid(item.ValueSchema) {
			return fmt.Errorf("%s has invalid valueSchema", item.ID)
		}
	}
	if len(value.Definitions) == 0 {
		return errors.New("registry has no schema definitions")
	}
	return nil
}

func generateGo(value registry, root string) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by tools/placetime13d-generate; DO NOT EDIT.\n")
	output.WriteString("package placetime13d\n\n")
	fmt.Fprintf(&output, "const GeneratedRegistryRoot = %q\n\n", root)
	output.WriteString("var GeneratedDimensions = []DimensionDescriptor{\n")
	for _, item := range value.Dimensions {
		fmt.Fprintf(
			&output,
			"\t{ID: %q, Name: %q, CoordinateClass: %q},\n",
			item.ID,
			item.Name,
			item.CoordinateClass,
		)
	}
	output.WriteString("}\n")
	return format.Source(output.Bytes())
}

func generateSchema(value registry, root string) ([]byte, error) {
	coordinateProperties := map[string]any{}
	requiredCoordinates := make([]string, 0, len(value.Dimensions))
	for _, item := range value.Dimensions {
		var schema any
		if err := json.Unmarshal(item.ValueSchema, &schema); err != nil {
			return nil, err
		}
		coordinateProperties[item.ID] = schema
		requiredCoordinates = append(requiredCoordinates, item.ID)
	}

	definitions := map[string]any{}
	keys := make([]string, 0, len(value.Definitions))
	for key := range value.Definitions {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		var definition any
		if err := json.Unmarshal(value.Definitions[key], &definition); err != nil {
			return nil, err
		}
		definitions[key] = definition
	}
	definitions["gitBinding"] = gitBindingSchema()
	definitions["permitReference"] = permitReferenceSchema()
	definitions["authorityProof"] = authorityProofSchema()

	schema := map[string]any{
		"$schema":              "https://json-schema.org/draft/2020-12/schema",
		"$id":                  "https://github.com/XRastlinX/logos-formal/registry/event_envelope.schema.json",
		"title":                "Placetime 13D Governed Git Event",
		"type":                 "object",
		"additionalProperties": false,
		"required": []string{
			"schema", "version", "eventId", "registryRoot", "bindingPhase", "artifactRoot",
			"parentEvents", "gitBinding", "coordinates", "requestedEffect", "authorityProof",
			"permitRef", "policyRoot", "decision", "authorityEffect", "validationReceipts",
		},
		"properties": map[string]any{
			"schema":       map[string]any{"const": "urn:logos-formal:placetime-13d-event:v0.1"},
			"version":      map[string]any{"const": "0.1.0"},
			"eventId":      map[string]any{"type": "string", "minLength": 1},
			"registryRoot": map[string]any{"const": root},
			"bindingPhase": map[string]any{"enum": []string{"PROPOSAL", "WITNESS"}},
			"artifactRoot": map[string]any{"$ref": "#/$defs/hashRef"},
			"parentEvents": map[string]any{
				"type":        "array",
				"uniqueItems": true,
				"items":       map[string]any{"type": "string", "minLength": 1},
			},
			"gitBinding": map[string]any{"$ref": "#/$defs/gitBinding"},
			"coordinates": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             requiredCoordinates,
				"properties":           coordinateProperties,
			},
			"requestedEffect": map[string]any{"enum": []string{"NONE", "READ", "STAGE", "APPLY"}},
			"authorityProof":  map[string]any{"$ref": "#/$defs/authorityProof"},
			"permitRef":       map[string]any{"$ref": "#/$defs/permitReference"},
			"policyRoot": map[string]any{
				"oneOf": []any{
					map[string]any{"type": "null"},
					map[string]any{"$ref": "#/$defs/hashRef"},
				},
			},
			"decision":        map[string]any{"enum": []string{"NONE", "OBSERVE_ONLY", "REJECT", "PERMIT_REQUIRED", "PERMITTED"}},
			"authorityEffect": map[string]any{"enum": []string{"NONE", "PERMITTED"}},
			"validationReceipts": map[string]any{
				"type":  "array",
				"items": map[string]any{"$ref": "#/$defs/hashRef"},
			},
		},
		"allOf": []any{
			map[string]any{
				"if": map[string]any{
					"properties": map[string]any{"bindingPhase": map[string]any{"const": "WITNESS"}},
				},
				"then": map[string]any{
					"properties": map[string]any{
						"gitBinding": map[string]any{
							"properties": map[string]any{
								"commitOid": map[string]any{"type": "string", "minLength": 1},
								"treeOid":   map[string]any{"type": "string", "minLength": 1},
							},
						},
					},
				},
			},
		},
		"$defs": definitions,
	}
	encoded, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

func gitBindingSchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required": []string{
			"repository", "objectFormat", "commitOid", "treeOid", "parentOids",
			"refAtObservation", "artifactRoot",
		},
		"properties": map[string]any{
			"repository":   map[string]any{"type": "string", "minLength": 1},
			"objectFormat": map[string]any{"enum": []string{"sha1", "sha256"}},
			"commitOid": map[string]any{
				"oneOf": []any{
					map[string]any{"type": "null"},
					map[string]any{"type": "string", "pattern": "^[0-9a-f]+$"},
				},
			},
			"treeOid": map[string]any{
				"oneOf": []any{
					map[string]any{"type": "null"},
					map[string]any{"type": "string", "pattern": "^[0-9a-f]+$"},
				},
			},
			"parentOids":       map[string]any{"type": "array", "uniqueItems": true, "items": map[string]any{"type": "string", "pattern": "^[0-9a-f]+$"}},
			"refAtObservation": map[string]any{"type": "string", "minLength": 1},
			"artifactRoot":     map[string]any{"$ref": "#/$defs/hashRef"},
		},
	}
}

func permitReferenceSchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"presence"},
		"properties": map[string]any{
			"presence": map[string]any{"enum": []string{"ABSENT", "PRESENT", "INVALID", "REVOKED"}},
			"id":       map[string]any{"type": "string", "minLength": 1},
			"root":     map[string]any{"$ref": "#/$defs/hashRef"},
		},
	}
}

func authorityProofSchema() map[string]any {
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"presence"},
		"properties": map[string]any{
			"presence": map[string]any{"enum": []string{"ABSENT", "PRESENT", "INVALID", "REVOKED", "NOT_APPLICABLE"}},
			"subject":  map[string]any{"type": "string", "minLength": 1},
			"root":     map[string]any{"$ref": "#/$defs/hashRef"},
		},
	}
}

func compareFile(path string, expected []byte) error {
	actual, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(actual, expected) {
		return fmt.Errorf("%s is stale; run go generate ./internal/placetime13d", path)
	}
	return nil
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func fatalIf(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
